# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://www.github.com/yztxwd'}
- {icon: 'twitter',    link: 'https://twitter.com/JianyuYang3'}
- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/jianyu-yang-2593a81b5/'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
